feat: add category in meta data
dotbitHQ/identicons pull request #7
Opened 2022-09-19 12:00 UTC by vecpeng

2022-09-29 11:19 UTC, zgayjjf requested changes

2022-09-29 11:19 UTC, zgayjjf commented on src/modules/tools.ts
> +function getReduplicationValue (values: string[], name: string) {
Great.
But Named Capture Group is not a high-frequency feature, and the compatibility seems not high.

https://caniuse.com/?search=named%20capture

So there should be a link to the tech spec for the convenience of other developers.
https://github.com/tc39/proposal-regexp-named-groups

2022-09-29 11:22 UTC, merged

2022-09-29 15:15 UTC, zgayjjf commented on package.json
> +    "rootDir": "./",
What's the purpose of changing it?

2022-09-30 09:12 UTC, vecpeng commented on package.json
> +    "rootDir": "./",
Keep the same style with dotbit.js.